#!/bin/bash

argv0="$1"
shift

if [[ $EUID -eq 0 ]]
then
  exec $argv0 "$@"
else
  exec sudo $argv0 "$@"
fi

echo "$(basename "$0"): error: $argv0: exec failed" >&2
exit 1

##
# vim: ts=2 sw=2 tw=100 et fdm=marker :
##
